# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUSIP', models.CharField(max_length=9)),
                ('description', models.TextField(max_length=200)),
                ('state', localflavor.us.models.USStateField()),
                ('quantity_min', models.IntegerField()),
                ('quantity_max', models.IntegerField()),
                ('years_min', models.DateTimeField()),
                ('years_max', models.DateTimeField()),
                ('coupon_min', models.IntegerField()),
                ('coupon_max', models.IntegerField()),
                ('price_min', models.IntegerField()),
                ('price_max', models.IntegerField()),
                ('Moodys_Rating_Minimum', models.CharField(choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('BBB', 'BBB'), ('BB', 'BB'), ('B', 'B'), ('CCC', 'CCC'), ('CC', 'CC'), ('C', 'C'), ('D', 'D')], default='AAA', max_length=4)),
                ('Moodys_Rating_Maximum', models.CharField(choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('BBB', 'BBB'), ('BB', 'BB'), ('B', 'B'), ('CCC', 'CCC'), ('CC', 'CC'), ('C', 'C'), ('D', 'D')], default='AAA', max_length=4)),
                ('SandP_Rating_Minimum', models.CharField(choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('BBB', 'BBB'), ('BB', 'BB'), ('B', 'B'), ('CCC', 'CCC'), ('CC', 'CC'), ('C', 'C'), ('D', 'D')], default='AAA', max_length=4)),
                ('SandP_Rating_Maximum', models.CharField(choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('BBB', 'BBB'), ('BB', 'BB'), ('B', 'B'), ('CCC', 'CCC'), ('CC', 'CC'), ('C', 'C'), ('D', 'D')], default='AAA', max_length=4)),
                ('Fitch_Ratings_Minimum', models.CharField(choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('BBB', 'BBB'), ('BB', 'BB'), ('B', 'B'), ('CCC', 'CCC'), ('CC', 'CC'), ('C', 'C'), ('D', 'D')], default='AAA', max_length=4)),
                ('Fitch_Ratings_Maximum', models.CharField(choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('BBB', 'BBB'), ('BB', 'BB'), ('B', 'B'), ('CCC', 'CCC'), ('CC', 'CC'), ('C', 'C'), ('D', 'D')], default='AAA', max_length=4)),
                ('Inventory_Choices', models.BooleanField(choices=[('All', 'All'), ('Street', 'Street'), ('Internal', 'Internal')], default='All', max_length=3)),
                ('Include_Choices', models.BooleanField(choices=[('Secondary', 'Secondary'), ('New Issues', 'New Issues'), ('Bids Wanted', 'Bids Wanted')], default='Secondary', max_length=3)),
                ('Limit_Offerings_Choices', models.BooleanField(choices=[('All', 'All'), ('Only New', 'Only New'), ('Only with a Quoted Bid Side', 'Only with a Quoted Bid Side')], default='All', max_length=3)),
                ('View', models.BooleanField(choices=[('Collapsed', 'Collapsed'), ('Expanded', 'Expanded')], default='Collapsed', max_length=2)),
                ('Spread', models.CharField(choices=[('bps', 'bps'), ('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], default='bps', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
