# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUSIP', models.CharField(max_length=9)),
                ('description', models.TextField(max_length=200)),
                ('quantity_min', models.IntegerField()),
                ('quantity_max', models.IntegerField()),
                ('years_min', models.DateTimeField()),
                ('years_max', models.DateTimeField()),
                ('coupon_min', models.IntegerField()),
                ('coupon_max', models.IntegerField()),
                ('price_min', models.IntegerField()),
                ('price_max', models.IntegerField()),
                ('Moodys_Rating_Minimum', models.CharField(choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('BBB', 'BBB'), ('BB', 'BB'), ('B', 'B'), ('CCC', 'CCC'), ('CC', 'CC'), ('C', 'C'), ('D', 'D')], default='AAA', max_length=4)),
                ('Moodys_Rating_Maximum', models.CharField(choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('BBB', 'BBB'), ('BB', 'BB'), ('B', 'B'), ('CCC', 'CCC'), ('CC', 'CC'), ('C', 'C'), ('D', 'D')], default='AAA', max_length=4)),
                ('SandP_Rating_Minimum', models.CharField(choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('BBB', 'BBB'), ('BB', 'BB'), ('B', 'B'), ('CCC', 'CCC'), ('CC', 'CC'), ('C', 'C'), ('D', 'D')], default='AAA', max_length=4)),
                ('SandP_Rating_Maximum', models.CharField(choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('BBB', 'BBB'), ('BB', 'BB'), ('B', 'B'), ('CCC', 'CCC'), ('CC', 'CC'), ('C', 'C'), ('D', 'D')], default='AAA', max_length=4)),
                ('Fitch_Ratings_Minimum', models.CharField(choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('BBB', 'BBB'), ('BB', 'BB'), ('B', 'B'), ('CCC', 'CCC'), ('CC', 'CC'), ('C', 'C'), ('D', 'D')], default='AAA', max_length=4)),
                ('Fitch_Ratings_Maximum', models.CharField(choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('BBB', 'BBB'), ('BB', 'BB'), ('B', 'B'), ('CCC', 'CCC'), ('CC', 'CC'), ('C', 'C'), ('D', 'D')], default='AAA', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
