# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_min', models.IntegerField()),
                ('quantity_max', models.IntegerField()),
                ('years_min', models.CharField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015)], max_length=4)),
                ('years_max', models.CharField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015)], max_length=4)),
                ('coupon_min', models.IntegerField()),
                ('coupon_max', models.IntegerField()),
                ('price_min', models.IntegerField()),
                ('price_max', models.IntegerField()),
                ('Moodys_Rating_Minimum', models.CharField(choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('BBB', 'BBB'), ('BB', 'BB'), ('B', 'B'), ('CCC', 'CCC'), ('CC', 'CC'), ('C', 'C'), ('D', 'D')], default='AAA', max_length=4)),
                ('Moodys_Rating_Maximum', models.CharField(choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('BBB', 'BBB'), ('BB', 'BB'), ('B', 'B'), ('CCC', 'CCC'), ('CC', 'CC'), ('C', 'C'), ('D', 'D')], default='AAA', max_length=4)),
                ('SandP_Rating_Minimum', models.CharField(choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('BBB', 'BBB'), ('BB', 'BB'), ('B', 'B'), ('CCC', 'CCC'), ('CC', 'CC'), ('C', 'C'), ('D', 'D')], default='AAA', max_length=4)),
                ('SandP_Rating_Maximum', models.CharField(choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('BBB', 'BBB'), ('BB', 'BB'), ('B', 'B'), ('CCC', 'CCC'), ('CC', 'CC'), ('C', 'C'), ('D', 'D')], default='AAA', max_length=4)),
                ('Fitch_Ratings_Minimum', models.CharField(choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('BBB', 'BBB'), ('BB', 'BB'), ('B', 'B'), ('CCC', 'CCC'), ('CC', 'CC'), ('C', 'C'), ('D', 'D')], default='AAA', max_length=4)),
                ('Fitch_Ratings_Maximum', models.CharField(choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('BBB', 'BBB'), ('BB', 'BB'), ('B', 'B'), ('CCC', 'CCC'), ('CC', 'CC'), ('C', 'C'), ('D', 'D')], default='AAA', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_type', models.CharField(choices=[("GO's", "GO's"), ("Rev's", "Rev's"), ('Double Brl', 'Double Brl')], default="GO's", max_length=3)),
                ('sectors', models.CharField(choices=[('All', 'All'), ('US Government', 'US Government'), ('Mortgage', 'Mortgage'), ('Credit', 'Credit'), ('Non-US', 'Non-US'), ('Cash', 'Cash')], default='All', max_length=20)),
                ('prerefund', models.CharField(choices=[('Onlyif', 'Onlyif'), ('Exclude', 'Exclude'), ('Include', 'Include')], default='Include', max_length=20)),
                ('escrowed', models.CharField(choices=[('Onlyif', 'Onlyif'), ('Exclude', 'Exclude'), ('Include', 'Include')], default='Include', max_length=20)),
                ('insured', models.CharField(choices=[('Onlyif', 'Onlyif'), ('Exclude', 'Exclude'), ('Include', 'Include')], default='Include', max_length=20)),
                ('insurable', models.CharField(choices=[('Onlyif', 'Onlyif'), ('Exclude', 'Exclude'), ('Include', 'Include')], default='Include', max_length=20)),
                ('taxable', models.CharField(choices=[('Onlyif', 'Onlyif'), ('Exclude', 'Exclude'), ('Include', 'Include')], default='Include', max_length=20)),
                ('amt', models.CharField(choices=[('Onlyif', 'Onlyif'), ('Exclude', 'Exclude'), ('Include', 'Include')], default='Include', max_length=20)),
                ('bank_q', models.CharField(choices=[('Onlyif', 'Onlyif'), ('Exclude', 'Exclude'), ('Include', 'Include')], default='Include', max_length=20)),
                ('callable', models.CharField(choices=[('Onlyif', 'Onlyif'), ('Exclude', 'Exclude'), ('Include', 'Include')], default='Include', max_length=20)),
                ('putable', models.CharField(choices=[('Onlyif', 'Onlyif'), ('Exclude', 'Exclude'), ('Include', 'Include')], default='Include', max_length=20)),
                ('float_var_rt', models.CharField(choices=[('Onlyif', 'Onlyif'), ('Exclude', 'Exclude'), ('Include', 'Include')], default='Include', max_length=20)),
                ('sinking_fund', models.CharField(choices=[('Onlyif', 'Onlyif'), ('Exclude', 'Exclude'), ('Include', 'Include')], default='Include', max_length=20)),
                ('convertible', models.CharField(choices=[('Onlyif', 'Onlyif'), ('Exclude', 'Exclude'), ('Include', 'Include')], default='Include', max_length=20)),
                ('zero_coupon', models.CharField(choices=[('Onlyif', 'Onlyif'), ('Exclude', 'Exclude'), ('Include', 'Include')], default='Include', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inventory_Choices', models.CharField(choices=[('All', 'All'), ('Street', 'Street'), ('Internal', 'Internal')], default='All', max_length=3)),
                ('Include_Choices', models.CharField(choices=[('Secondary', 'Secondary'), ('New Issues', 'New Issues'), ('Bids Wanted', 'Bids Wanted')], default='Secondary', max_length=3)),
                ('Limit_Offerings_Choices', models.CharField(choices=[('All', 'All'), ('Only New', 'Only New'), ('Only with a Quoted Bid Side', 'Only with a Quoted Bid Side')], default='All', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='QuickSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', localflavor.us.models.USStateField()),
                ('CUSIP', models.CharField(max_length=9)),
                ('description', models.TextField(max_length=200)),
                ('Spread', models.CharField(choices=[('bps', 'bps'), ('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], default='bps', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
