# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160620_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='Include_Choices',
            new_name='include_choices',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='Inventory_Choices',
            new_name='inventory_choices',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='Limit_Offerings_Choices',
            new_name='limit_offerings_choices',
        ),
        migrations.AddField(
            model_name='market',
            name='window',
            field=models.BooleanField(choices=[('Collapsed', 'Collapsed'), ('Expanded', 'Expanded')], default='Collapsed', max_length=2),
        ),
        migrations.AlterField(
            model_name='broadrange',
            name='years_max',
            field=models.CharField(choices=[('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001')], max_length=4),
        ),
        migrations.AlterField(
            model_name='broadrange',
            name='years_min',
            field=models.CharField(choices=[('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001')], max_length=4),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='bond_type',
            field=models.CharField(choices=[("GO's", "GO's"), ("Rev's", "Rev's"), ('Double Brl', 'Double Brl')], default="GO's", max_length=20),
        ),
        migrations.AlterField(
            model_name='quicksearch',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
