# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160624_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broadrange',
            old_name='Fitch_Ratings_Maximum',
            new_name='Merrill_Lynch_Maximum',
        ),
        migrations.RenameField(
            model_name='broadrange',
            old_name='Fitch_Ratings_Minimum',
            new_name='Merrill_Lynch_Minimum',
        ),
        migrations.RemoveField(
            model_name='broadrange',
            name='SandP_Rating_Maximum',
        ),
        migrations.RemoveField(
            model_name='broadrange',
            name='SandP_Rating_Minimum',
        ),
        migrations.RemoveField(
            model_name='broadrange',
            name='coupon_max',
        ),
        migrations.RemoveField(
            model_name='broadrange',
            name='coupon_min',
        ),
        migrations.RemoveField(
            model_name='broadrange',
            name='price_max',
        ),
        migrations.RemoveField(
            model_name='broadrange',
            name='price_min',
        ),
        migrations.RemoveField(
            model_name='broadrange',
            name='quantity_max',
        ),
        migrations.RemoveField(
            model_name='broadrange',
            name='quantity_min',
        ),
        migrations.RemoveField(
            model_name='broadrange',
            name='years_max',
        ),
        migrations.RemoveField(
            model_name='broadrange',
            name='years_min',
        ),
        migrations.AddField(
            model_name='broadrange',
            name='Federal_Reserve',
            field=models.CharField(choices=[('Nominal Potential Gross Domestic Product', 'Nominal Potential Gross Domestic Product'), ('Natural Rate of Unemployment (Short-Term)', 'Natural Rate of Unemployment (Short-Term)'), ('Natural Rate of Unemployment (Long-Term)', 'Natural Rate of Unemployment (Long-Term)')], default=None, max_length=4),
        ),
    ]
